# Generated by Django 5.1.6 on 2025-03-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_recipeingredient_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='quantity',
        ),
    ]
