# Generated by Django 5.1.6 on 2025-03-01 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_remove_recipeingredient_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='name',
            new_name='quantity',
        ),
    ]
